services:
  webserver:
    build: ./
    ports:
      - "8088:80"
    networks:
      - front
      - db
    environment:
      DB_NAME: django
      DB_USERNAME: djangouser
      DB_PASS: djangopass
      DB_HOST: postgres
      DB_PORT: 5432
      MIGRATOR_DB_USER: djangomigratoruser
      MIGRATOR_DB_PASS: djangomigratorpass

  postgres:
    image: postgres:9.6-alpine
    volumes:
      - ./configs/postgres-init:/docker-entrypoint-initdb.d/
    restart: always
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: 'pgAdminPassword'
      PGDATA: '/db'
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: django
      DB_USER: djangouser
      DB_PASS: djangopass
      MIGRATOR_DB_USER: djangomigratoruser
      MIGRATOR_DB_PASS: djangomigratorpass
networks:
  front:
  db:
    internal: true



